spring.application.name=KPCompany01
spring.datasource.url=jdbc:mysql://localhost:3306/KPCompany
spring.datasource.username=root
spring.datasource.password=kproqkf!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true